### PR TITLE
Increase the existing race condition sleep to 10s

### PR DESCRIPTION
**Pull request by cajun-rat**
The 'fixes' bug PRO-801, where the AGL demo UI fails to start on Arthur's
laptop.  It does this by increasing the already existing sleep commands from
2/3 seconds to 5/10 seconds.

It also pulls directly from the openivimobility github, which is a bit easier
than managing patches in bitbake.

### CODE REVIEW

**Comment by cajun-rat** [comment]
cc @leon-anavi 

From Arthur's email:

Works! :)

Thanks,

Arthur

**Comment by leon-anavi** [comment]
Hi @cajun-rat, @OYTIS,

OK, the work around seems good enough for a demo. Could you please have a look at my pull request and merge them both?

Thanks, Leon

**Comment by cajun-rat** [comment]
@OYTIS nudge :)

**Comment by OYTIS** [comment]
Review score 20/26

**Pull request merged**
